# Uncomment this line to define a global platform for your project
platform :osx, '10.10'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Snub' do
    pod 'CocoaLumberjack', '2.1.0-beta'
end

target 'SnubTests' do

end

target 'SnubUITests' do

end

