platform :osx, '10.10'
use_frameworks!

target 'Snub' do
    pod 'CocoaLumberjack', '2.1.0-beta'
    pod 'PDKTZipArchive', :git => 'https://github.com/ashokgelal/PDKTZipArchive'
    pod 'SwiftRegExp', '~> 1.0'
    pod 'Async', :git => 'https://github.com/JohnCoates/Async.git'
    pod 'FuzzySearch', :git => 'https://github.com/ashokgelal/FuzzySearch'
end

target 'SnubTests' do

end

target 'SnubUITests' do

end

