platform :osx, '10.10'
use_frameworks!

target 'Snub' do
    pod 'CocoaLumberjack', '2.1.0-beta'
    pod 'PDKTZipArchive', :git => 'https://github.com/JoeMatt/PDKTZipArchive'
end

target 'SnubTests' do

end

target 'SnubUITests' do

end

