platform :osx, '10.10'
use_frameworks!

workspace 'Snub.xcworkspace'

xcodeproj 'SnubCore/SnubCore.xcodeproj'
target 'SnubCore' do
    pod 'LogKit'
    pod 'PDKTZipArchive', :git => 'https://github.com/ashokgelal/PDKTZipArchive'
    #pod 'SwiftRegExp', '~> 1.3'
    pod 'SwiftRegExp', :git => 'https://github.com/ashokgelal/SwiftRegExp'
end

target 'Snub' do
    xcodeproj 'Snub/Snub.xcodeproj'
    pod 'LogKit'
    pod 'PDKTZipArchive', :git => 'https://github.com/ashokgelal/PDKTZipArchive'
    pod 'AsyncSwift'
    pod 'FuzzySearch', :git => 'https://github.com/ashokgelal/FuzzySearch'
    pod 'SwiftRegExp', :git => 'https://github.com/ashokgelal/SwiftRegExp'
    #pod 'SwiftRegExp', '~> 1.3'
    pod 'Sparkle', '~> 1.10'
end

